name: Download Site and Process Code

on:
  issue_comment:
    types: [created]
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  download-and-process:
    name: Download site, modify code, and commit changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl gzip sed

      - name: Run webflow-scraper/download_site.sh script
        run: |
          chmod +x webflow-scraper/download_site.sh
          chmod +x webflow-scraper/generate_sitemap.sh
          ./webflow-scraper/download_site.sh
          mv robots.txt dist/
          mv build/* dist/

      - name: Commit and push changes
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git
          git add dist
          git commit -m "Updated site from Webflow" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}

      - name: Verify changes were committed
        run: |
          echo "✅ All changes have been committed and pushed successfully"
          echo "The upload workflow will now trigger automatically"
