# on:
#   push:
#     branches:
#       - master

# name: Build and Publish Averment
# jobs:
#   FTP-Deploy-Action:
#     name: FTP-Deploy-Action
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master

#       - name: Use Node.js 10.18.1
#         uses: actions/setup-node@v1
#         with:
#           node-version: "10.18.1"

#       - name: Build Project
#         run: |
#           npm install
#           npm run build --if-present

# #      - name: Checkout
# #        uses: actions/checkout@v2.3.4

#       - name: List output files
#         run: ls

#       - name: Upload Files
#         id: upload
#         uses: Creepios/sftp-action@v1.0.3
#         with:
#           host: ${{ secrets.FTP_SERVER }}
#           port: 22
#           username: ${{ secrets.FTP_USERNAME }}
#           password: ${{ secrets.FTP_PASSWORD }}
#           localPath: "./dist"
#           remotePath: "/dist"

#   # - name: Deploy file
#   #   uses: wlixcc/SFTP-Deploy-Action@v1.2.4
#   #   with:
#   #       username: ${{ secrets.FTP_USERNAME }}
#   #       server: ${{ secrets.FTP_SERVER }}
#   #       port: 22
#   #       local_path: './dist'
#   #       remote_path: '/'
#   #       sftp_only: true
#   #       password: ${{ secrets.FTP_PASSWORD }}

on:
  push:
    branches:
      - master

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local-dir: "./dist/asssets"
          server-dir: "/musikversicherung"
